// Optimization: power profiles, CPU boost, swappiness, cache drop.

import { call, onTelemetry } from "../lib/bridge";
import { h, icon, toast } from "../lib/ui";
import type { View } from "../app";

const PROFILES = [
  { id: "performance", icon: "bolt", name: "Performance", desc: "Max clocks, fans unleashed. For benchmarks and heavy builds." },
  { id: "balanced", icon: "scale", name: "Balanced", desc: "Adaptive clocks and power. The everyday default." },
  { id: "power-saver", icon: "leaf", name: "Power Saver", desc: "Lowest draw, cool and quiet. Squeeze the battery." },
];

export class OptimizeView implements View {
  private unsub: (() => void) | null = null;
  private info: any = null;

  async mount(root: HTMLElement) {
    const cards = new Map<string, HTMLElement>();
    const cardsWrap = h("div", { class: "profile-cards" });
    for (const p of PROFILES) {
      const card = h(
        "div",
        {
          class: "profile-card",
          onclick: async () => {
            try {
              await call("sysopt_set_profile", { profile: p.id });
              toast(`Profile → ${p.name}`);
              this.setActive(cards, p.id);
            } catch (e) {
              toast(String(e), true);
            }
          },
        },
        icon(p.icon, 30),
        h("div", { class: "name" }, p.name),
        h("div", { class: "desc" }, p.desc),
      );
      cards.set(p.id, card);
      cardsWrap.append(card);
    }

    // live power draw panel
    const watts = h("span", { class: "live" }, "—");
    const rows = h("div");

    root.append(
      h(
        "div",
        { class: "view-header" },
        h("h2", { html: "SYSTEM <b>OPTIMIZATION</b>" }),
        h("span", { class: "sub" }, "profiles · toggles · tuning"),
        h("div", { class: "spacer" }),
        h("div", { class: "readout accent" }, h("span", { class: "k" }, "TOTAL DRAW"), watts),
      ),
      cardsWrap,
      h(
        "section",
        { class: "panel" },
        h("div", { class: "panel-head" }, icon("settings"), h("span", { class: "t" }, "Tuning Console")),
        h("div", { class: "panel-body" }, rows),
      ),
      this.buildAiModules(),
    );

    this.unsub = onTelemetry((s) => {
      watts.textContent = `${(s.power.cpu_watts + s.gpu.watts).toFixed(1)} W`;
    });

    await this.loadTuning(rows, cards);
  }

  /// AI-generated optimization modules: the model reads the live system
  /// state and proposes reviewed, one-click-apply command modules.
  private buildAiModules(): HTMLElement {
    const out = h("div");
    const note = h(
      "div",
      { class: "bench-note" },
      "Modules are generated by your configured AI from the live system state. Commands are always shown for review — nothing runs without your Apply, and root modules go through the system auth dialog.",
    );

    const render = (data: { state: string; modules: any[]; filtered: number }) => {
      out.innerHTML = "";
      out.append(
        h("div", { class: "ai-result-label", style: { marginTop: "10px" } }, "SYSTEM STATE SENT TO MODEL"),
        h("pre", { class: "ai-mod-pre dim" }, data.state.trim()),
      );
      if (data.filtered > 0) {
        out.append(h("div", { class: "bench-note" }, `${data.filtered} module(s) removed by safety rules.`));
      }
      for (const m of data.modules) {
        const result = h("div", { class: "ai-mod-out" });
        const applyBtn = h(
          "button",
          {
            class: "btn ghost",
            onclick: async () => {
              (applyBtn as HTMLButtonElement).disabled = true;
              applyBtn.textContent = "APPLYING…";
              try {
                const res = await call<string>("ai_optimize_apply", {
                  commands: m.commands,
                  requiresRoot: !!m.requires_root,
                });
                result.textContent = res;
                toast(`${m.title} — applied`);
              } catch (e) {
                result.textContent = String(e);
                toast(String(e), true);
              }
              (applyBtn as HTMLButtonElement).disabled = false;
              applyBtn.innerHTML = "";
              applyBtn.append(icon("play"), "Apply");
            },
          },
          icon("play"),
          "Apply",
        );
        out.append(
          h(
            "div",
            { class: "ai-mod" },
            h(
              "div",
              { class: "ai-mod-head" },
              h("span", { class: "mod-title" }, m.title),
              h("span", { class: `mod-badge ${m.impact}` }, `impact ${m.impact}`),
              h("span", { class: `mod-badge ${m.risk === "safe" ? "safe" : "caution"}` }, m.risk),
              m.requires_root ? h("span", { class: "mod-badge root" }, "root") : null,
              h("div", { class: "spacer" }),
              applyBtn,
            ),
            h("div", { class: "mod-rationale" }, m.rationale),
            h("pre", { class: "ai-mod-pre" }, m.commands.join("\n")),
            result,
          ),
        );
      }
    };

    const genBtn = h(
      "button",
      {
        class: "btn",
        onclick: async () => {
          (genBtn as HTMLButtonElement).disabled = true;
          genBtn.textContent = "ANALYZING…";
          out.innerHTML = "";
          out.append(h("div", { class: "bench-note" }, "reading system state → asking the model for tailored modules…"));
          try {
            render(await call("ai_optimize_generate"));
          } catch (e) {
            out.innerHTML = "";
            toast(String(e), true);
            out.append(h("div", { class: "bench-note" }, String(e)));
          }
          (genBtn as HTMLButtonElement).disabled = false;
          genBtn.innerHTML = "";
          genBtn.append(icon("spark"), "Generate");
        },
      },
      icon("spark"),
      "Generate",
    );

    return h(
      "section",
      { class: "panel", style: { marginTop: "14px" } },
      h(
        "div",
        { class: "panel-head" },
        icon("spark"),
        h("span", { class: "t" }, "AI Optimization Modules"),
        h("div", { class: "spacer" }),
        genBtn,
      ),
      h("div", { class: "panel-body" }, note, out),
    );
  }

  private async loadTuning(rows: HTMLElement, cards: Map<string, HTMLElement>) {
    try {
      this.info = await call<any>("sysopt_get");
    } catch (e) {
      rows.append(h("div", { class: "bench-note" }, String(e)));
      return;
    }
    const info = this.info;
    this.setActive(cards, info.profile);

    const optRow = (t: string, d: string, control: HTMLElement) =>
      h("div", { class: "opt-row" }, h("div", { class: "info" }, h("div", { class: "t" }, t), h("div", { class: "d" }, d)), control);

    // CPU boost
    if (info.boost !== null && info.boost !== undefined) {
      const sw = h("button", { class: `switch${info.boost ? " on" : ""}` });
      sw.onclick = async () => {
        const target = !sw.classList.contains("on");
        try {
          await call("sysopt_set_boost", { on: target });
          sw.classList.toggle("on", target);
          toast(`CPU boost ${target ? "enabled" : "disabled"}`);
        } catch (e) {
          toast(String(e), true);
        }
      };
      rows.append(optRow("CPU Boost", "Turbo frequencies above base clock (needs authorization).", sw));
    }

    // swappiness
    const swapVal = h("span", { class: "val" }, String(info.swappiness));
    const slider = h("input", { type: "range", min: "0", max: "150", value: String(info.swappiness) }) as HTMLInputElement;
    slider.oninput = () => (swapVal.textContent = slider.value);
    const applyBtn = h(
      "button",
      {
        class: "btn ghost",
        onclick: async () => {
          try {
            await call("sysopt_set_swappiness", { value: Number(slider.value) });
            toast(`Swappiness → ${slider.value}`);
          } catch (e) {
            toast(String(e), true);
          }
        },
      },
      "Apply",
    );
    rows.append(
      optRow("Swappiness", "How aggressively memory pages move to swap. Lower keeps apps in RAM.",
        h("div", { style: { display: "flex", alignItems: "center", gap: "10px" } }, slider, swapVal, applyBtn)),
    );

    // core balancing
    const balanceOut = h("div", { class: "bench-note", style: { display: "none" } });
    rows.append(
      optRow("Core Balancing", "Bring all cores online, unify the governor across them, enable autogroup scheduling and spread IRQs.",
        h(
          "button",
          {
            class: "btn",
            onclick: async (e: Event) => {
              const b = e.currentTarget as HTMLButtonElement;
              b.disabled = true;
              try {
                const res = await call<string>("sysopt_balance_cores");
                balanceOut.textContent = res;
                balanceOut.style.display = "";
                toast("Cores balanced");
              } catch (err) {
                toast(String(err), true);
              }
              b.disabled = false;
            },
          },
          icon("cpu"),
          "Balance",
        )),
      balanceOut,
    );

    // drop caches
    rows.append(
      optRow("Drop Caches", "Flush pagecache, dentries and inodes. Frees RAM instantly; next file reads are colder.",
        h(
          "button",
          {
            class: "btn",
            onclick: async (e: Event) => {
              const b = e.currentTarget as HTMLButtonElement;
              b.disabled = true;
              try {
                await call("sysopt_drop_caches");
                toast("Caches dropped");
              } catch (err) {
                toast(String(err), true);
              }
              b.disabled = false;
            },
          },
          icon("refresh"),
          "Flush",
        )),
    );

    // readouts
    rows.append(
      optRow("CPU Governor", "Kernel frequency scaling policy currently in charge.",
        h("span", { class: "val", style: { minWidth: "auto" } }, info.governor || "—")),
    );
    if (info.epp) {
      rows.append(
        optRow("Energy-Performance Preference", "Hardware hint balancing speed vs efficiency (amd/intel pstate).",
          h("span", { class: "val", style: { minWidth: "auto" } }, info.epp)),
      );
    }
  }

  private setActive(cards: Map<string, HTMLElement>, id: string) {
    for (const [pid, el] of cards) {
      el.classList.toggle("active", pid === id);
      el.querySelector(".status-dot")?.remove();
      if (pid === id) el.append(h("div", { class: "status-dot" }));
    }
  }

  unmount() {
    this.unsub?.();
  }
}
